foodorder/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

import home
from foodorder import settings
from home import views
from order import views as OrderViews
from user import views as UserViews




urlpatterns = [

    path('home/', views.index, name='home'),
    path('', views.index, name='home'),
    path('about/', views.aboutus, name='about'),
    path('order/', include('order.urls')),
    path('contact/', views.contactus, name='contact'),
    path('home/about/', views.aboutus, name='about'),
    path('search/', views.search, name='search'),
    path('auto_search/', views.search, name='auto_search'),
    path('home/contact/', views.contactus, name='contact'),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('category/<int:id>/<slug:slug>', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('shopcart/', OrderViews.shopcart, name='shopcart'),
    path('login/', UserViews.login_form, name='login_form'),
    path('logout/', UserViews.logout_fuc, name='logout_ffunc'),
    path('signup/', UserViews.signup_form, name='signup_form'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from user.views import user_update
from . import views

urlpatterns = [
    path('home', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    path('update/', views.user_update, name='user_update'),

]

order/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct', views.orderproduct, name='orderproduct'),
]

order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm

from product.models import Product


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    @property
    def price(self):
        return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.product.price)

    @property
    def varamount(self):
        return (self.quantity * self.variant.price)


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']

class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False )
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','address','phone','city','country']

class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.IntegerField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

order/views.py
from ckeditor_uploader.utils import get_random_string
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.crypto import get_random_string

from home.models import Setting
from order.models import ShopCart, ShopCartForm, OrderForm, Order, OrderProduct
from product.models import Category, Product
from user.models import UserProfile



def index(request):
    return HttpResponse ("Order Page")

@login_required(login_url='/login') # Check login
def addtoshopcart(request,id):

    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user  # Access User Session information

    checkproduct = ShopCart.objects.filter(product_id=id) # Check product in shopcart
    if checkproduct:
        control = 1 # The product is in the cart
    else:
        control = 0 # The product is not in the cart

    if request.method == 'POST':  # if there is a post
        form = ShopCartForm(request.POST)
        if form.is_valid():
           if control==1: # Update  shopcart
                data = ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save()
           else : # Inser to Shopcart
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id =id
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, "Product added to Shopcart ")
        return HttpResponseRedirect(url)

    else: # if there is no post
        if control == 1:  # Update  shopcart
            data = ShopCart.objects.get(product_id=id)
            data.quantity += 1
            data.save()
        else:  #  Inser to Shopcart
            data = ShopCart()  # model ile bağlantı kur
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.save()
        messages.success(request, "Product added to Shopcart")
        return HttpResponseRedirect(url)


def shopcart(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    current_user = request.user  # Access User Session information
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total=0
    for rs in shopcart:
        total +=  rs.price * rs.quantity
    #return HttpResponse(str(total))
    context={'shopcart': shopcart,
             'category':category,
             'setting':setting,
             'total': total,
             }
    return render(request,'shopcart_products.html',context)


@login_required(login_url='/login') # Check login
def deletefromcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, "Your item deleted form Shopcart.")
    return HttpResponseRedirect("/shopcart")


def orderproduct(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    current_user = request.user
    schopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in schopcart:
        total = rs.product.price * rs.quantity

    if request.method == 'POST':  # if there is a post
        form = OrderForm(request.POST)
        #return HttpResponse(request.POST.items())
        if form.is_valid():
            # Send Credit card to bank,  If the bank responds ok, continue, if not, show the error
            # ..............
            data = Order()
            data.first_name = form.cleaned_data['first_name'] #get product quantity from form
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode= get_random_string(5).upper() # random cod
            data.code =  ordercode
            data.save() #

            # Move  Shopcart items to Order Products items
            schopcart = ShopCart.objects.filter(user_id=current_user.id)
            for rs in schopcart:
                detail = OrderProduct()
                detail.order_id     = data.id # Order Id
                detail.product_id   = rs.product_id
                detail.user_id      = current_user.id
                detail.quantity     = rs.quantity
                detail.price        = rs.product.price
                detail.amount        = rs.amount
                detail.save()
                # ***Reduce quantity of sold product from Amount of Product
                product = Product.objects.get(id=rs.product_id)
                product.amount = rs.quantity
                product.save()
                #************ <> *****************

            ShopCart.objects.filter(user_id=current_user.id).delete() # Clear & Delete shopcart
            request.session['cart_items']=0
            messages.success(request, "Your Order has been completed. Thank you ")
            return render(request, 'Order_Completed.html',{'ordercode':ordercode,'category': category})
        else:
            messages.warning(request, form.errors)


    form= OrderForm()
    schopcart = ShopCart.objects.filter(user_id=current_user.id)
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'schopcart': schopcart,
               'category': category,
               'total': total,
               'form': form,
               'profile': profile,
               'setting': setting,
               }
    return render(request, 'Order_Form.html', context)

order/templates/Order_Completed.html
{% extends 'homebase.html' %}
{% load static %}
{% load mptt_tags %}
{% block header %}{% include "header.html" %}{% endblock %}


    {% block title %} ORDER COMPLETED-{{ setting.title }} {% endblock %}
    {% block keywords %}  {{ setting.keywords }} {% endblock %}
    {% block description %}  {{ setting.description }} {% endblock %}
    <!-- Start header -->

{% block content %}

    <!-- BREADCRUMB -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>ORDER COMPLETED</h1>
				</div>
			</div>
		</div>
	</div>>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Order Complated</h3>
                        </div>
                        <hr>
                        <h2>Dear  {{ user.first_name }} {{  user.last_name }}</h2>
                        <hr>
                        <h3>Your order is completed</h3>
                        <h3>Order Code : {{ ordercode }}</h3>
                        <h3>wish you liked the meal</h3>
                        <hr>

                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}
{% block footer %}{% include "footer.html" %}{% endblock %}

order/templates/Order_Form.html
{% extends 'homebase.html' %}
{% load static %}
{% load mptt_tags %}
{% block header %}{% include "header.html" %}{% endblock %}


{% block title %} ORDER FORM-{{ setting.title }} {% endblock %}
{% block keywords %}  {{ setting.keywords }} {% endblock %}
{% block description %}  {{ setting.description }} {% endblock %}
<!-- Start header -->

{% block content %}

    <!-- BREADCRUMB -->
    <div class="all-page-title page-breadcrumb">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h1>ORDER FROM</h1>
                </div>
            </div>
        </div>
    </div>


    <div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <form id="checkout-form" class="clearfix" method="post">
                {% csrf_token %}
                <div class="col-md-6">
                    <div class="billing-details">

                        <div class="section-title">
                            <h4 class="title">Shipping Details</h4>
                        </div>
                        <p><label for="id_first_name">First name:</label>
                            <input type="text" name="first_name" value="{{ user.first_name }}" class="input"
                                   maxlength="10" required id="id_first_name"></p>
                        <p><label for="id_last_name">Last name:</label>
                            <input type="text" name="last_name" value="{{ user.last_name }}" class="input"
                                   maxlength="10" required id="id_last_name"></p>
                        <p><label for="id_address">Address:</label>
                            <input type="text" name="address" value="{{ profile.address }}" class="input"
                                   maxlength="150" id="id_address"></p>
                        <p><label for="id_phone">Phone:</label>
                            <input type="text" name="phone" value="{{ profile.phone }}" class="input" maxlength="20"
                                   id="id_phone"></p>
                        <p><label for="id_city">City:</label>
                            <select name="city" class="input" id="id_city">
                                <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                <option value="İstanbul">Istanbul</option>
                                <option value="İstanbul">mersin</option>
                                <option value="Ankara">Ankara</option>
                                <option value="İzmir">Izmir</option>
                                <option value="Bursa">Bursa</option>
                                <option value="Konya">Konya</option>
                                <option value="Yozgat">Yozgat</option>
                            </select></p>
                        <p><label for="id_first_name">Country :</label>
                            <input type="text" name="country" class="input" id="id_country"
                                   value="{{ profile.country }}"></p>
                        <div class="pull-right">
                            <button type="submit" class="primary-btn">Complete Order</button>
                        </div>
                    </div>
                </div>
            </Form>

            <div class="col-md-6">


                <form id="checkout-form" class="clearfix" method="post">
                    {% csrf_token %}
                    <form class="col-md-6">
                        <div class="billing-details">
                            <div class="shiping-methods">
                                <div class="section-title">
                                    <h4 class="title">Payment Information</h4>
                                </div>
                                <p><label for="id_first_name">Total:</label>
                                    <input type="text" name="total" class="input" readonly value="${{ total }}"></p>
                                <p><label for="id_first_name">Credit Card Holder</label>
                                    <input type="text" name="holder" class="input" value=""></p>
                                <p><label for="id_first_name">Credit Card Number</label>
                                    <input type="text" name="number" class="input" value=""></p>
                                <p><label for="id_first_name">Credit Exp Date/Year</label>
                                    <input type="text" name="ecpdate" class="input" placeholder="mm/yy"></p>
                                <p><label for="id_first_name">Security Number</label>
                                    <input type="text" name="secnumber" class="input" value=""></p>
                            </div>
                        </div>





            </div>
               <div class="col-md-12">
                            <div class="order-summary clearfix">
                                <div class="section-title">
                                    <h3 class="title">Shopcart Product List</h3>
                                </div>
                                <table class="shopping-cart-table table">
                                    <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th></th>
                                        <th class="text-center">Price</th>
                                        <th class="text-center">Quantity</th>
                                        <th class="text-center">Total</th>
                                        <th class="text-right"></th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for rs in shopcart %}
                                        <tr>
                                            <td class="thumb"><img src="{{ rs.product.image.url }}" alt=""></td>
                                            <td class="details"><a
                                                    href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">{{ rs.product }}</a>
                                            </td>
                                            <td class="price text-center"><strong>${{ rs.product.price }}</strong></td>
                                            <td class="qty text-center"><strong>{{ rs.quantity }}</strong></td>
                                            <td class="total text-center"><strong
                                                    class="primary-color">${{ rs.amount }}</strong></td>
                                            <td class="text-right"><a href="/order/deletefromcart/{{ rs.id }}"
                                                                      onclick="return confirm('Delete ! Are you sure?')"
                                                                      class="main-btn icon-btn"><i
                                                    class="fa fa-close"></i></a></td>
                                        </tr>

                                    {% endfor %}

                                    </tbody>
                                    <tfoot>

                                    <tr>
                                        <th class="empty" colspan="3"></th>
                                        <th>TOTAL</th>
                                        <th colspan="2" class="total">${{ total }}</th>
                                    </tr>
                                    </tfoot>
                                </table>
                                <div class="pull-right">
                                    <button>
                                        <a href="/order/orderproduct" class="primary-btn">Place Order</a>
                                    </button>
                                </div>
                            </div>

                        </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->




{% endblock %}
{% block footer %}{% include "footer.html" %}{% endblock %}

order/templates/shopcart_products.html
{% extends 'homebase.html' %}
{% load static %}
{% load mptt_tags %}
{% block header %}{% include "header.html" %}{% endblock %}


    {% block title %} shopcart- {{ setting.title }} {% endblock %}
    {% block keywords %}  {{ setting.keywords }} {% endblock %}
    {% block description %}  {{ setting.description }} {% endblock %}
    <!-- Start header -->

{% block content %}

    <!-- BREADCRUMB -->
    <div class="all-page-title page-breadcrumb">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h1>shop cart</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                        </div>
                        <table class="shopping-cart-table table">
                            <thead>
                            <tr>
                                <th>Product</th>
                                <th></th>
                                <th class="text-center">Price</th>
                                <th class="text-center">Quantity</th>
                                <th class="text-center">Total</th>
                                <th class="text-right"></th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for rs in shopcart %}
                                <tr>
                                    <td class="thumb"><img src="{{rs.product.image.url}}" height="150" alt=""></td>
                                    <td class="details"><a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">{{rs.product}}</a>  </td>
                                    <td class="price text-center"><strong>${{rs.product.price}}</strong></td>
                                    <td class="qty text-center"><strong>{{rs.quantity}}</strong></td>
                                    <td class="total text-center"><strong class="primary-color">${{rs.amount}}</strong></td>
                                    <td class="text-right"><a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Delete ! Are you sure?')" class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
                                </tr>

                            {% endfor %}

                            </tbody>
                            <tfoot>

                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>TOTAL</th>
                                <th colspan="2" class="total">${{ total }}</th>
                            </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right">
                            <button>
                            <a href="/order/orderproduct" class="primary-btn">Place Order</a>
                                </button>
                        </div>
                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}
{% block footer %}{% include "footer.html" %}{% endblock %}